server:
  port:
    8090

dubbo:
  application:                #dubbo应用名称
    name: springboot-admin
  consumer:                   #启动时不检查提供者是否已经注册
    check: false
  registry:                   #zookeeper 注册中心地址
    address: zookeeper://127.0.01:2181